export const NOTIFICATION_TYPE = {
  USER_REGISTERED: 'USER_REGISTERED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET: 'PASSWORD_RESET',
  TAX_ORDER_CREATED: 'TAX_ORDER_CREATED',
  TAX_ORDER_UPDATED: 'TAX_ORDER_UPDATED',
  DOCUMENTS_UPLOADED: 'DOCUMENTS_UPLOADED',
  TAX_ORDER_PLACED: 'TAX_ORDER_PLACED',
  TAX_AMOUNTS_UPDATED: 'TAX_AMOUNTS_UPDATED',
  PAYMENT_INITIATED: 'PAYMENT_INITIATED',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_CANCELLED: 'PAYMENT_CANCELLED',
  FILE_UPLOADED: 'FILE_UPLOADED',
  FILE_DELETED: 'FILE_DELETED',
  NEWS_PUBLISHED: 'NEWS_PUBLISHED',
  NEWS_UPDATED: 'NEWS_UPDATED',
} as const;

export type TNotificationType =
  (typeof NOTIFICATION_TYPE)[keyof typeof NOTIFICATION_TYPE];
